---
# See https://github.com/DavidAnson/markdownlint#optionsconfig
# and https://github.com/DavidAnson/markdownlint-cli2
config:
  emphasis-style: true
  line-length:
    code_blocks: false
    line_length: 300
  no-blanks-blockquote: false
  no-space-in-emphasis: true
  strong-style: true
  ul-style: consistent
