---
extends: default
ignore:
  - bin/
  - bundle/   # These are generated files so linting them is problematic
  - config/   # These are generated files so linting them is problematic
  - git/
  - testbin/
  - vendor/
  - telco5g-konflux/
rules:
  line-length: disable
