apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
generatorOptions:
  disableNameSuffixHash: true
images:
- name: controller
  newName: quay.io/openshift-kni/lifecycle-agent-operator
  newTag: 4.19.0
kind: Kustomization
patches:
- path: related-images/patch.yaml
resources:
- manager.yaml
