apiVersion: v1
kind: Namespace
metadata:
  annotations:
    workload.openshift.io/allowed: management
  labels:
    app.kubernetes.io/component: lifecycle-agent
    app.kubernetes.io/name: lifecycle-agent-operator
    control-plane: controller-manager
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: lifecycle-agent
    app.kubernetes.io/name: lifecycle-agent-operator
    control-plane: controller-manager
  name: controller-manager
  namespace: system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: lifecycle-agent
      app.kubernetes.io/name: lifecycle-agent-operator
      control-plane: controller-manager
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        openshift.io/scc: privileged
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      labels:
        app.kubernetes.io/component: lifecycle-agent
        app.kubernetes.io/name: lifecycle-agent-operator
        control-plane: controller-manager
    spec:
      containers:
        - command:
            - /usr/local/bin/manager
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: controller:latest
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 20Mi
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
          tty: true
          volumeMounts:
            - mountPath: /host
              name: host-root
      hostPID: true
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
        - hostPath:
            path: /
            type: Directory
          name: host-root
