apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    health:
      healthProbeBindAddress: :8081
    kind: ControllerManagerConfig
    leaderElection:
      leaderElect: false
      resourceName: lca.openshift.io
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
kind: ConfigMap
metadata:
  name: lifecycle-agent-manager-config
