apiVersion: lca.openshift.io/v1
kind: ImageBasedUpgrade
metadata:
  name: upgrade
spec:
  autoRollbackOnFailure: {}
  extraManifests:
    - name: sno-extramanifests
      namespace: openshift-lifecycle-agent
  oadpContent:
    - name: oadp-cm-sno-backup
      namespace: openshift-adp
  seedImageRef:
    image: quay.io/xyz
    version: 4.14.0
  stage: Idle
