# This file is for teaching kustomize how to substitute name and namespace reference in CRD
nameReference:
  - fieldSpecs:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        path: spec/conversion/webhook/clientConfig/service/name
        version: v1
    kind: Service
    version: v1
namespace:
  - create: false
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    path: spec/conversion/webhook/clientConfig/service/namespace
    version: v1
varReference:
  - path: metadata/annotations
