---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: controller-manager
spec:
  podSelector:
    matchLabels:
      control-plane: controller-manager
  egress:
     - {} # Allow egress to all destinations and ports
  policyTypes:
    - Egress
